# Use an officail Ubuntu base image 
From ubuntu 22.04 

# Install Python and pip 
RUN apt-get update  && \ 
    apt-get install -y python3 python3-pip

# Set the working directory in the container 
WORKDIR /app

# Copy the working directory contents in the container 
COPY . /app

#Install and needed dependencies specified in init.py 
RUN pip3 install --no-cache-dir - r init.py       
